/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Action: typeof import('./src/components/ActionBar.vue')['default']
    ActionBar: typeof import('./src/components/ActionBar.vue')['default']
    DarkSwitcher: typeof import('./src/components/DarkSwitcher.vue')['default']
    Hello: typeof import('./src/components/Hello.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    SelectionOverlay: typeof import('./src/components/SelectionOverlay.vue')['default']
    Time: typeof import('./src/components/TimeSchedular.vue')['default']
    TimeDial: typeof import('./src/components/TimeDial.vue')['default']
    TimeSchedular: typeof import('./src/components/TimeSchedular.vue')['default']
    TimezoneItem: typeof import('./src/components/TimezoneItem.vue')['default']
    TimezoneSearch: typeof import('./src/components/TimezoneSearch.vue')['default']
  }
}
