/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Action: typeof import('./src/components/ActionBar.vue')['default']
    ActionBar: typeof import('./src/components/ActionBar.vue')['default']
    Hello: typeof import('./src/components/Hello.vue')['default']
    Time: typeof import('./src/components/TimeSchedular.vue')['default']
    TimeSchedular: typeof import('./src/components/TimeSchedular.vue')['default']
    TimezoneSearch: typeof import('./src/components/TimezoneSearch.vue')['default']
  }
}
